Setup travis build deployment

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,9 +4,48 @@ sudo: false
 go:
   - 1.8.x
   - 1.9.x
+  - master
 
 install:
   - go get -d -v ./...
 
 script:
   - go test -v ./...
+
+before_deploy:
+  # Script copied from https://github.com/zabawaba99/go-travis-github-release/
+  - PLATFORMS=(darwin/amd64 linux/amd64 windows/amd64)
+  - |
+    for PLATFORM in "${PLATFORMS[@]}"; do
+      echo "Building $PLATFORM"
+      GOOS=${PLATFORM%/*}
+      GOARCH=${PLATFORM#*/}
+      if [ "$GOOS" = "windows" ]; then
+        build_cmd="GOOS=$GOOS GOARCH=$GOARCH go build -o sshsyrup.exe -ldflags '-w -s'"
+      else
+        build_cmd="CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o sshsyrup -ldflags '-w -s'"
+      fi
+      if ! eval $build_cmd; then
+        echo "Failed building sshsyrup for $PLATFORM" && return 1
+      fi
+      if [ "$GOOS" = "windows" ]; then
+        zip sshsyrup${TRAVIS_TAG}-${GOOS}-${GOARCH}.zip sshsyrup.exe
+      else
+        tar cvzf sshsyrup${TRAVIS_TAG}-${GOOS}-${GOARCH}.tar.gz sshsyrup
+      fi
+    done
+  - ls
+
+deploy:
+  provider: releases
+  api_key: $AUTH_TOKEN
+  file:
+    - "sshsyrup${TRAVIS_TAG}-darwin-amd64.tgz"
+    - "sshsyrup${TRAVIS_TAG}-linux-amd64.tgz"
+    - "sshsyrup${TRAVIS_TAG}-windows-amd64.zip"
+
+  skip_cleanup: true
+  on:
+    go: 1.9.x
+    branch: master
+    tags: true
